version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 jenkins:
  image: iapolinario/jenkins:latest
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
  depends_on:
    - nexus
    - gitlab
    - sonar
    - selhub
  environment:
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  build: iapolinario/sonar:latest
  ports:
   - "19000:9000"
   - "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
 
 sonardb:
  networks:
    - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

